sudo: required
language: java
jdk: 
    - oraclejdk11
services:
    - docker
branches:
    only:
    - master
    except:
    - dev 
env:
    global:
      - SHA=$(git rev-parse HEAD)
 
before_install:     
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - cd dit-spring-boot-project
script:
- mvn clean install -DskipTests
 
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS