sudo: required
language: java
jdk: 
    - openjdk
services:
    - docker
branches:
    only:
    - master
    except:
    - dev 
env:
    global:
      - SHA=$(git rev-parse HEAD)
 
before_install:     
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - mv my-spa-app/dist/my-spa-app/* dit-spring-boot-project/src/main/resources/static
    - cd dit-spring-boot-project
script:
- mvn clean install -DskipTests